/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PetParentRole;

import Business.EcoSystem;
import Business.PetTherapy.PetParent;
import Business.PetTherapy.PetParentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PTherapy;
import Business.WorkQueue.Pet;
import Business.WorkQueue.PetQueue;
import Business.WorkQueue.PetTherapyQueue;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.MainJFrame;

/**
 *
 * @author Krish
 */
public class PetParentJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form PetParentJPanel
     */
    
    private EcoSystem system;
    private PetTherapyQueue pettherapyqueue;
    private PetParentDirectory petparentdirectory;
    private PetParent parent;
    
        
    public PetParentJPanel(JPanel UserProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        //setLabel();
        this.system = system;
        this.petparentdirectory = system.getPettherapydirectory().getPetparentdir();
        this.pettherapyqueue= system.getPettherapydirectory().getPettherapyqueue();
        parent = system.getPettherapydirectory().getPetparentdir().RetrievePetParent(MainJFrame.txtUsernameMain.getText());
        
        populatepetsTable();
        
        
    }
    
    public void populatePetRequests(PTherapy ptherapy, DefaultTableModel model){
        
        
        if(ptherapy.getAccept()!=null){
        if(ptherapy.getAccept()==false){
            
            return;
        }
        }
        
        
        
        
        Object[] row = new Object[6];
        row[0]= ptherapy.getId();
        row[1]= ptherapy.getStudentid();
        row[2]= ptherapy.getDate();
        row[3] = ptherapy.getTime();
        if(ptherapy.getAccept()==null){
            
            row[4]= "Please Update Status";
        }
        
        if(ptherapy.getAccept()!=null){
        if(ptherapy.getAccept()==true){
            
            row[4] = "Accepted";
        }
        }
        
        row[5]= ptherapy.getLocation();
        model.insertRow(0, row);
        
        
        
        
        
        
    }
    
    public void populatepetsTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblDogList.getModel();
        model.setRowCount(0);
        if(parent==null){
            parent = system.getPettherapydirectory().getPetparentdir().RetrievePetParent(MainJFrame.txtUsernameMain.getText());
            
            
        }
        
        if(parent.getPetQueue()==null){
            
            PetQueue petqueue = new PetQueue();
            parent.setPetQueue(petqueue);
        }
        
        if(parent.getPetQueue().getPetlist()==null){
            
            ArrayList <Pet> petlist = new ArrayList();
            parent.getPetQueue().setPetlist(petlist);
        }
        
        for(Pet pet: parent.getPetQueue().getPetlist()){
            
            Object[] row = new Object[4];
            row[0]= pet.getId();
            row[1]= pet.getName();
            row[2] = pet.getBreed();
            row[3] = pet.getAge();
           
            
            model.insertRow(0, row);
            
            
        }
    }
    
    /**public void setLabel(){
        
        if(parent==null){
            parent = system.getPettherapydirectory().getPetparentdir().RetrievePetParent(MainJFrame.txtUsernameMain.getText());
            
        }
        
        lblValue.setText(parent.getId());
    }**/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblCreate = new javax.swing.JLabel();
        lblPetnm = new javax.swing.JLabel();
        lblBreed = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblLike = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        lblUpload = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        txtFilenm1 = new javax.swing.JTextField();
        lblImage1 = new javax.swing.JLabel();
        txtPetnm = new javax.swing.JTextField();
        txtBreed = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtlike = new javax.swing.JTextField();
        txtFood = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblWelcome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDogList = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        enterpriseLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        lblLocation = new javax.swing.JLabel();
        cbcLocation = new javax.swing.JComboBox<>();
        btnAccept = new javax.swing.JButton();
        lblReason = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        btnReject = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblWelcome.setBackground(new java.awt.Color(255, 255, 0));
        lblWelcome.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 0, 51));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Pet Parent! It's great to see you again!");

        lblCreate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblCreate.setForeground(new java.awt.Color(153, 0, 51));
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Spread some happiness by registering your pet here!");

        lblPetnm.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPetnm.setText("Name:");

        lblBreed.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBreed.setText("Breed:");

        lblAge.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblAge.setText("Age:");

        lblLike.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLike.setText("Favourite activity:");

        lblFood.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblFood.setText("Favourite food:");

        lblUpload.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblUpload.setForeground(new java.awt.Color(153, 0, 51));
        lblUpload.setText("Add a picture here! ");

        btnUpload.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtFilenm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilenm1ActionPerformed(evt);
            }
        });

        lblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage1.setText("Dog Image");
        lblImage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSave.setText("Save Details");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
            .addComponent(lblCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFilenm1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLike, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFood, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlike, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPetnm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPetnm, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtBreed, txtFood, txtPetnm, txtlike});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblBreed, lblFood, lblLike, lblPetnm});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetnm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPetnm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLike, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlike, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFood, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpload)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilenm1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAge, lblBreed, lblFood, lblLike, lblPetnm, txtAge, txtBreed, txtFood, txtPetnm, txtlike});

        jTabbedPane1.addTab("Register your pet", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        lblWelcome1.setBackground(new java.awt.Color(255, 255, 0));
        lblWelcome1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(153, 0, 51));
        lblWelcome1.setText("Manage you appointments here!");

        tblDogList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Breed"
            }
        ));
        jScrollPane1.setViewportView(tblDogList);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pettherapy (1).jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRequest.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRequest.setText("View Requests");
        btnRequest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        enterpriseLabel1.setBackground(new java.awt.Color(255, 255, 0));
        enterpriseLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enterpriseLabel1.setText("Requestor details:");

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RequestID", "Name", "Date requested", "Time requested", "Status", "Location"
            }
        ));
        jScrollPane3.setViewportView(tblRequest);

        lblLocation.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLocation.setText("Pick location:");

        cbcLocation.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        cbcLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "RICHARDS GARDEN", "CENTENIAL GARDEN", "NEU GROUND AREA" }));

        btnAccept.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAccept.setText("Accept request!");
        btnAccept.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblReason.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblReason.setForeground(new java.awt.Color(153, 0, 51));
        lblReason.setText("You can also reject the request! Please specify a reason:");

        btnReject.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnReject.setText("Reject request!");
        btnReject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAccept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbcLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblReason, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReject, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtReason))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblWelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReason, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Appointments", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        Pet pet = parent.getPetQueue().addPet();
        String name = txtPetnm.getText();
        String breed = txtBreed.getText();
        String age = txtAge.getText();
        
        String likes = txtlike.getText();
        String food = txtFood.getText();
        String filename = txtFilenm1.getText();
        
        pet.setAge(age);
        pet.setBreed(breed);
        pet.setFilename(filename);
        pet.setFood(food);
        pet.setLikes(likes);
        pet.setName(name);
         JOptionPane.showMessageDialog(this, "Uploaded dog");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFilenm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilenm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilenm1ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed

        JFileChooser chooser1 = new JFileChooser();
        chooser1.showOpenDialog(null);
        File f = chooser1.getSelectedFile();
     String filename = f.getAbsolutePath();
     txtFilenm1.setText(filename);
     Image getAbsolutePath = null;
     ImageIcon icon = new ImageIcon(filename);
     
     Image image = icon.getImage().getScaledInstance(lblImage1.getWidth(), lblImage1.getHeight(), Image.SCALE_SMOOTH);
     lblImage1.setIcon(new ImageIcon(image));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelOrder = (DefaultTableModel)tblDogList.getModel();
        int selectedIndex = tblDogList.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);
        if(selectedIndex==-1){
            
            JOptionPane.showMessageDialog(this, "Please Select a Dog");
            return;
            
        }
        String therapistid = null;
        
        if(selectedIndex!=-1){
            
             therapistid = modelOrder.getValueAt(selectedIndex, 0).toString();
        }
        
        int petid = Integer.parseInt(therapistid);
        
        for(PTherapy student: pettherapyqueue.getPTherapylist()){
            
            if(student.getPetid()==petid){
                
                populatePetRequests(student,model);
            }
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelOrder = (DefaultTableModel)tblRequest.getModel();
        int selectedIndex = tblRequest.getSelectedRow();
        if(selectedIndex==-1){
            
            JOptionPane.showMessageDialog(this, "Please Select a Request");
            return;
            
        }
        String therapistid = null;
        
        if(selectedIndex!=-1){
            
             therapistid = modelOrder.getValueAt(selectedIndex, 0).toString();
        }
        
        int ptid = Integer.parseInt(therapistid);
        
        PTherapy ptherapy = pettherapyqueue.retrievePTherapy(ptid);
        
        ptherapy.setAccept(Boolean.TRUE);
        
        ptherapy.setLocation(cbcLocation.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(this, "Accepted!");
        
        
        
        
        
        
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel modelOrder = (DefaultTableModel)tblRequest.getModel();
        int selectedIndex = tblRequest.getSelectedRow();
        if(selectedIndex==-1){
            
            JOptionPane.showMessageDialog(this, "Please Select a Request");
            return;
            
        }
        String therapistid = null;
        
        if(selectedIndex!=-1){
            
             therapistid = modelOrder.getValueAt(selectedIndex, 0).toString();
        }
        
        int ptid = Integer.parseInt(therapistid);
        
        PTherapy ptherapy = pettherapyqueue.retrievePTherapy(ptid);
        
        ptherapy.setAccept(Boolean.FALSE);
        
        //ptherapy.setLocation(cbcLocation.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(this, "Rejected");
    }//GEN-LAST:event_btnRejectActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cbcLocation;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBreed;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblLike;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPetnm;
    private javax.swing.JLabel lblReason;
    private javax.swing.JLabel lblUpload;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JTable tblDogList;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtFilenm1;
    private javax.swing.JTextField txtFood;
    private javax.swing.JTextField txtPetnm;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTextField txtlike;
    // End of variables declaration//GEN-END:variables
}
