/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.University.Volunteer;
import Business.University.VolunteerDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Event;
import Business.WorkQueue.EventQueue;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.MainJFrame;

/**
 *
 * @author Varakumar
 */
public class VolunteerRoleWorkArea extends javax.swing.JPanel {
    
    private JPanel UserProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private Volunteer volunteer;
    private VolunteerDirectory volunteerdirectory;
    private EventQueue eventqueue;
    

    /**
     * Creates new form VolunteerRoleWorkArea
     */
    public VolunteerRoleWorkArea(JPanel UserProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.account=account;
        this.system=system;
        this.volunteer = system.getUniversitydirectory().getVolunteerdir().RetrieveVolunteer(MainJFrame.txtUsernameMain.getText());
        this.volunteerdirectory = system.getUniversitydirectory().getVolunteerdir();
        this.eventqueue = system.getUniversitydirectory().getEventqueue();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtForum = new javax.swing.JTextArea();
        lblForum1 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtFilenm = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        calendarSession = new com.toedter.calendar.JCalendar();
        cbcSlot = new javax.swing.JComboBox<>();
        txtTitle = new javax.swing.JTextField();
        lblForum2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblForum.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblForum.setText("Post:");
        add(lblForum, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 299, 96, 25));

        txtForum.setColumns(20);
        txtForum.setRows(5);
        jScrollPane1.setViewportView(txtForum);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 299, 530, 148));

        lblForum1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblForum1.setForeground(new java.awt.Color(153, 0, 51));
        lblForum1.setText("Add a poster here!");
        add(lblForum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 190, 199, 33));

        btnImage.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnImage.setText("Click to Upload");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 236, 180, 33));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 96, 221, 263));

        btnSave.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 599, 187, -1));
        add(txtFilenm, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 192, 427, 33));

        lblDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDate.setText("Date:");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 513, 96, 25));
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 515, 187, 25));

        lblLocation.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLocation.setText("Location:");
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 468, 96, 25));
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 187, 25));
        add(calendarSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 468, 421, 213));

        cbcSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Slot", "8:00 ", "9:00 ", "10:00 ", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00","17:00","18:00","19:00","20:00","21:00" }));
        add(cbcSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 558, 187, 30));
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 136, 530, 36));

        lblForum2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblForum2.setText("Title:");
        add(lblForum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 134, 96, 36));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome, Volunteer! ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 820, 31));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Taking initiative is brave! We're grateful for your contribution. ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 810, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Add new event here!");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 96, 222, 27));
    }// </editor-fold>//GEN-END:initComponents
 
    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed

JFileChooser chooser1 = new JFileChooser();
        chooser1.showOpenDialog(null);
        File f = chooser1.getSelectedFile();
     String filename = f.getAbsolutePath();
     txtFilenm.setText(filename);
     Image getAbsolutePath = null;
     ImageIcon icon = new ImageIcon(filename);
     
     Image image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
     lblImage.setIcon(new ImageIcon(image));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    
     Calendar cal = calendarSession.getCalendar();
        
     Date date = cal.getTime();
     String strDate = DateFormat.getDateInstance().format(date);
     txtDate.setText(strDate);
        
     String slot = cbcSlot.getSelectedItem().toString();
     Event event = eventqueue.addEvent();
     Random rand = new Random();
     int random = rand.nextInt(12345);
     event.setId(random);
     String ev = txtForum.getText();
     if(ev==null){
         
         JOptionPane.showMessageDialog(this, "There is no description!");
         return;
         
         
     }
    
    String image = txtFilenm.getText();
    event.setDat(strDate);
    Date d = new Date();
    event.setDate(d);
    event.setFilename(image);
    event.setLocation(txtLocation.getText());
    event.setTime(cbcSlot.getSelectedItem().toString());
    event.setForum(ev);
    event.setPostedby(volunteer.getId());
    JOptionPane.showMessageDialog(this, "Uploaded!");
    
    


        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JCalendar calendarSession;
    private javax.swing.JComboBox<String> cbcSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblForum;
    private javax.swing.JLabel lblForum1;
    private javax.swing.JLabel lblForum2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFilenm;
    private javax.swing.JTextArea txtForum;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
