/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NutritionistRole;

import Business.EcoSystem;
import Business.MindFitness.NutrionistDirectory;
import Business.MindFitness.Nutritionist;
import Business.University.StudentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NutritionistAppointment;
import Business.WorkQueue.NutritionistAppointmentQueue;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.MainJFrame;

/**
 *
 * @author Varakumar
 */
public class NutritionistWorkArea extends javax.swing.JPanel {
    
    private JPanel UserProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    NutritionistAppointmentQueue nutriqueue;
    NutrionistDirectory nutridir;
    StudentDirectory studentdirectory;
    Nutritionist nutritionist;

    /**
     * Creates new form NutritionistWorkArea
     */
    public NutritionistWorkArea(JPanel UserProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.account=account;
        this.system=system;
        this.nutridir = system.getMindfitnessdir().getNutridir();
        this.nutriqueue = system.getMindfitnessdir().getNutriqueue();
        this.studentdirectory = system.getUniversitydirectory().getStudentdir();
        nutritionist=system.getMindfitnessdir().getNutridir().RetrieveNutritionist(MainJFrame.txtUsernameMain.getText());
        
    }
    
    public void populateAppointmentTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblAppointmentDetails.getModel();
        model.setRowCount(0);
        
        for(NutritionistAppointment app: nutriqueue.getNutritionistAppointmentlist()){
            
            if(app.getNutritionistid().equals(nutritionist.getId())){
            
            if(app.getTerminate()==false){
                
                Object[] row = new Object[6];
                row[0]= app.getId();
                
                row[1]= app.getStudentid();
                row[2] = studentdirectory.RetrieveStudent(app.getStudentid()).getName();
                row[3]= app.getDate();
                row[4] = app.getTime();
                row[5] = "Upcoming";
                
                
                model.insertRow(0, row);
            }
            
            else{
                Object[] row = new Object[6];
                row[0]= app.getId();
                
                row[1]= app.getStudentid();
                row[2] = studentdirectory.RetrieveStudent(app.getStudentid()).getName();
                row[3]= app.getDate();
                row[4] = app.getTime();
                row[5] = "Session Completed";
                
                
                model.insertRow(0, row);
                
            }
        }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnTerminate2 = new javax.swing.JButton();
        lblSpecial = new javax.swing.JLabel();
        txtSpecial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointmentDetails = new javax.swing.JTable();
        btnTerminate3 = new javax.swing.JButton();
        btnTerminate4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setBackground(new java.awt.Color(255, 255, 0));
        lblWelcome.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome, Nutritionist!");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 793, 30));

        btnTerminate2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTerminate2.setText("Refresh Table");
        btnTerminate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminate2ActionPerformed(evt);
            }
        });
        add(btnTerminate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 355, 180, 32));

        lblSpecial.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSpecial.setText("Speciality:");
        lblSpecial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(lblSpecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 74, 140, 27));
        add(txtSpecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 76, 161, 27));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Manage appointments:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 152, 435, 27));

        tblAppointmentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "SessionID", "StudentID", "Name", "Date", "Time", "Appointment Status"
            }
        ));
        jScrollPane1.setViewportView(tblAppointmentDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 190, 656, 154));

        btnTerminate3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTerminate3.setText("Terminate Session");
        btnTerminate3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTerminate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminate3ActionPerformed(evt);
            }
        });
        add(btnTerminate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 398, 180, 32));

        btnTerminate4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTerminate4.setText("Save");
        btnTerminate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminate4ActionPerformed(evt);
            }
        });
        add(btnTerminate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 114, 84, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminate2ActionPerformed
        // TODO add your handling code here:
        
        populateAppointmentTable();
    }//GEN-LAST:event_btnTerminate2ActionPerformed

    private void btnTerminate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminate3ActionPerformed
        // TODO add your handling code here:
        
        System.out.print("I am in button\n");
        DefaultTableModel modelOrder = (DefaultTableModel)tblAppointmentDetails.getModel();
        int selectedIndex = tblAppointmentDetails.getSelectedRow();
        if(selectedIndex==-1){
            
            JOptionPane.showMessageDialog(this, "Please Select a row!");
            return;
            
        }
        String id=null;
        
        if(selectedIndex!=-1){
            
             id = modelOrder.getValueAt(selectedIndex, 0).toString();
             //createdby = modelOrder.getValueAt(selectedIndex, 2).toString();
        }
        int intid = Integer.parseInt(id);
        
        
        NutritionistAppointment therapy = nutriqueue.retrieveNutritionistAppointment(intid);
        //System.out.print(therapy.getTerminate() +" this is terminate\n");
        therapy.setTerminate(Boolean.TRUE);
        //system.getUniversitydirectory().getStudentdir().RetrieveStudent(therapy.getStudentid()).setAppointment(Boolean.FALSE);
        JOptionPane.showMessageDialog(this, "Terminated!");
        
        
    }//GEN-LAST:event_btnTerminate3ActionPerformed

    private void btnTerminate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminate4ActionPerformed
        // TODO add your handling code here:
        
        nutritionist.setSpeciality(txtSpecial.getText());
        JOptionPane.showMessageDialog(this, "Saved");
    }//GEN-LAST:event_btnTerminate4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminate2;
    private javax.swing.JButton btnTerminate3;
    private javax.swing.JButton btnTerminate4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSpecial;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblAppointmentDetails;
    private javax.swing.JTextField txtSpecial;
    // End of variables declaration//GEN-END:variables
}
